# Generated by Django 3.0.4 on 2020-04-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='job',
            new_name='product',
        ),
    ]
