# Generated by Django 3.0.4 on 2020-05-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200502_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s', to='accounts.Specialist'),
        ),
    ]
