# Generated by Django 3.0.4 on 2020-05-03 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20200503_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist', to=settings.AUTH_USER_MODEL),
        ),
    ]
