# Generated by Django 3.0.4 on 2020-05-04 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20200504_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('order in process', 'order in process'), ('delivered', 'delivered')], max_length=200, null=True)),
                ('specialist2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Specialist2')),
            ],
        ),
    ]
