# Generated by Django 3.0.4 on 2020-05-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_order2_specialist2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist2',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order2',
        ),
        migrations.DeleteModel(
            name='Specialist2',
        ),
    ]
